# Sr. Architect Approved Analysis Options
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # --- Style & Cleanliness ---
    prefer_single_quotes: true
    directives_ordering: true
    require_trailing_commas: true # Clean diffs
    sort_child_properties_last: true
    unnecessary_this: true
    prefer_initializing_formals: true

    # --- Logic & Safety ---
    avoid_print: true
    always_declare_return_types: true
    unawaited_futures: true # Prevent async leakage
    avoid_relative_lib_imports: true
    prefer_const_constructors: true
    prefer_is_not_empty: true
    avoid_empty_else: true

    # --- Architectural Rigor ---
    package_api_docs: false
    public_member_api_docs: false # Switch to true for local packages
    sort_pub_dependencies: true
    avoid_type_to_string: true
