name: "🐛 Bug Report"
description: "Report a bug to help improve PassVault."
labels: ["bug"]
assignees: ["dhruvanbhalara"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: "Steps to reproduce the behavior."
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: "Flutter version, OS, Device model, etc."
      placeholder: "e.g. Flutter 3.19.0, Android 14, Pixel 7"
    validations:
      required: true
  - type: textarea
    id: additionals
    attributes:
      label: Additional Context
      description: "Add any other context or screenshots about the problem here."
