name: Setup Flutter Environment
description: |
  Composite action to consolidate Flutter SDK setup and dependency installation.
  Uses flutter-action's built-in caching for both SDK and pub packages.

runs:
  using: composite
  steps:
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true # Caches both Flutter SDK and pub packages

    - name: Disable Flutter analytics
      shell: bash
      run: flutter config --no-analytics

    - name: Get dependencies
      shell: bash
      run: flutter pub get

    - name: Generate localization
      shell: bash
      run: flutter gen-l10n

    - name: Generate code (build_runner)
      shell: bash
      run: dart run build_runner build --delete-conflicting-outputs
