import 'dart:io';

void main(List<String> arguments) async {
  final lcovFile = File('coverage/lcov.info');
  if (!await lcovFile.exists()) {
    stderr.writeln('Error: coverage/lcov.info not found.');
    exit(1);
  }

  final lines = await lcovFile.readAsLines();
  int totalLF = 0; // Total lines foundation
  int totalLH = 0; // Total lines hit

  for (final line in lines) {
    if (line.startsWith('LF:')) {
      totalLF += int.parse(line.split(':')[1]);
    } else if (line.startsWith('LH:')) {
      totalLH += int.parse(line.split(':')[1]);
    }
  }

  if (totalLF == 0) {
    stderr.writeln('Error: No coverage data found in lcov.info.');
    exit(1);
  }

  final coveragePercent = (totalLH / totalLF) * 100;
  final formattedPercent = coveragePercent.toStringAsFixed(2);

  if (arguments.contains('--badge')) {
    String color = 'blue';
    if (coveragePercent < 50) {
      color = 'red';
    } else if (coveragePercent < 80) {
      color = 'yellow';
    } else {
      color = 'brightgreen';
    }

    stdout.writeln(
      '![Coverage](https://img.shields.io/badge/coverage-$formattedPercent%25-$color)',
    );
    return;
  }

  final report =
      '''
<!-- COVERAGE_START -->
## 📊 Code Coverage Report
| Metric | Value |
| :--- | :--- |
| **Total Lines** | $totalLF |
| **Lines Hit** | $totalLH |
| **Overall Coverage** | **$formattedPercent%** |

_Generated by PassVault CI_
<!-- COVERAGE_END -->
''';

  stdout.writeln(report);
}
